local obs = require('obsidian').get_client()

vim.keymap.set("n", "<leader>ocn", function()
  local t = vim.fn.input('Note name: ')
  vim.print(t)
  obs.switch_workspace(obs,'my-notes')
  local note = obs.create_note(obs, { title = t, id = t })
  vim.cmd('vsplit')
  vim.cmd('wincmd w')
  obs.open_note(obs, note)
end)

vim.keymap.set("n", "<leader>otd", function()
  obs.switch_workspace(obs,'my-notes')
  local note = obs.today(obs)
  vim.cmd('vsplit')
  vim.cmd('wincmd w')
  obs.open_note(obs, note)
end)

-- For work notes
vim.keymap.set("n", "<leader>owcn", function()
  local t = vim.fn.input('Note name: ')
  vim.print(t)
  obs.switch_workspace(obs,'work')
  local note = obs.create_note(obs, { title = t, id = t })
  vim.cmd('vsplit')
  vim.cmd('wincmd w')
  obs.open_note(obs, note)
end)

vim.keymap.set("n", "<leader>owtd", function()
  obs.switch_workspace(obs,'work')
  local note = obs.today(obs)
  vim.cmd('vsplit')
  vim.cmd('wincmd w')
  obs.open_note(obs, note)
end)
